wallpaper{
    monitor =
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}
wallpaper{
    monitor = "desc:Synaptics Inc Non-PnP 0x00BC614E"
    path = ~/.config/hypr/vertical-wallpaper.jpg
    fit_mode = cover
}
splash = false
