wallpaper {
    monitor =  desc:Philips Consumer Electronics Company 24B2U3301 UK02536017045
    path = ~/.config/hypr/vertical-wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

splash = false
